# This holds the configuration information
# using this config file will create KLCv3.0 compatible footprints.

lib_name_format_str: "Connector_Phoenix_{series:s}{suffix:s}"
manufacturer: "PhoenixContact"
fp_name_format_string: '{man:s}_{mpn:s}_{num_rows:d}x{num_pins:02d}_P{pitch:.2f}mm_{orientation:s}{flanged:s}{mount_hole:s}'
mpn_format_string: '{subseries:s}_{rating:s}_{num_pins:d}-{style:s}{pitch:s}'
mpn_format_string_no_rating: '{subseries:s}_{num_pins:d}-{style:s}{pitch:s}'
mpn_format_string_description: '{subseries:s}_{rating:s}/{num_pins:d}-{style:s}{pitch:s}'
mpn_format_string_description_no_rating: '{subseries:s}/{num_pins:d}-{style:s}{pitch:s}'
3d_model_prefix: '${KISYS3DMOD}/'
keywords_format_string: 'phoenix_contact connector {param_name:s}'
orientation_str: ['Vertical', 'Horizontal']
flanged_str: ['', '_ThreadedFlange']
mount_hole_str: ['', '_MountHole']
pin_layers: ['*.Cu', '*.Mask']
mount_hole_layers: ['*.Cu', '*.Mask']
with_fab_layer :  True
inner_details_on_fab : False
courtyard_for_mountscrews : True
